import Link from "next/link";
import "./globals.css";

import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Artmedia Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
